import os
from datetime import datetime
from fpdf import FPDF
from typing import Dict, Any, List, Optional
import json

class CallSheetPDF(FPDF):
    def __init__(self, project_name: str, shoot_day: int, shoot_date: str, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.project_name = project_name
        self.shoot_day = shoot_day
        self.shoot_date = shoot_date

    def header(self):
        # Logo / Header
        self.set_font("helvetica", "B", 18)
        self.cell(0, 10, f"CALL SHEET - {self.project_name.upper()}", align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_font("helvetica", "", 12)
        self.cell(0, 10, f"Shoot Day {self.shoot_day} | Date: {self.shoot_date}", align="C", new_x="LMARGIN", new_y="NEXT")
        self.line(10, 30, 200, 30)
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.cell(0, 10, f"Generated by CineSched | Page {self.page_no()}/{{nb}}", align="C")

def _safe_float(val, default=0.0):
    try:
        return float(val)
    except (ValueError, TypeError):
        return default

def generate_call_sheet(
    project: Any, 
    schedule: Any, 
    day: int, 
    scenes: List[Any], 
    cast: List[Any], 
    user_id: Optional[str] = None
) -> str:
    """
    Generates a PDF call sheet for a specific shoot day.
    If user_id is provided, generates a personalized call sheet (only their scenes).
    Returns the file path to the generated PDF.
    """
    # Create temp directory if not exists
    os.makedirs("/tmp/cinesched", exist_ok=True)
    file_path = f"/tmp/cinesched/callsheet_{project.id}_day_{day}{'_me' if user_id else ''}.pdf"

    # Filter schedule entries for this day
    day_entries = [e for e in schedule.entries if e.shoot_day == day]
    day_entries.sort(key=lambda e: e.start_time or datetime.min.time())
    
    shoot_date_str = "TBD"
    if day_entries and day_entries[0].shoot_date:
        shoot_date_str = day_entries[0].shoot_date.strftime("%Y-%m-%d")

    # If personalized, check if the user is in the cast, and only include their scenes
    personal_cast_member = None
    if user_id:
        personal_cast_member = next((c for c in cast if str(c.user_id) == str(user_id) or (getattr(c, 'user', None) and str(c.user.id) == str(user_id))), None)
        if personal_cast_member:
            filtered_entries = []
            for entry in day_entries:
                sc = next((s for s in scenes if str(s.id) == str(entry.scene_id)), None)
                if sc and any(str(cm.id) == str(personal_cast_member.id) for cm in getattr(sc, 'cast_members', [])):
                    filtered_entries.append(entry)
            day_entries = filtered_entries

    pdf = CallSheetPDF(project.name, day, shoot_date_str)
    pdf.add_page()

    # Weather Info (from schedule extra_context if available)
    if schedule.extra_context and "day_forecasts" in schedule.extra_context:
        forecasts = schedule.extra_context["day_forecasts"]
        if str(day) in forecasts:
            weather = forecasts[str(day)]
            pdf.set_font("helvetica", "B", 12)
            pdf.cell(0, 10, "Weather Forecast", new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("helvetica", "", 10)
            
            temp_max = weather.get("temperature_2m_max")
            temp_min = weather.get("temperature_2m_min")
            precip = weather.get("precipitation_probability_max")
            precip_mm = weather.get("precipitation_sum_mm")
            wind = weather.get("wind_speed_max_kmh")
            wcode = weather.get("weather_code")
            
            if temp_max is not None and temp_min is not None:
                pdf.cell(0, 6, f"Temperature Range: {temp_min:.1f}C to {temp_max:.1f}C", new_x="LMARGIN", new_y="NEXT")
            elif temp_max is not None or temp_min is not None:
                # Fallback to display whatever temperature values are present
                t_val = temp_max if temp_max is not None else temp_min
                pdf.cell(0, 6, f"Temperature: {t_val:.1f}C", new_x="LMARGIN", new_y="NEXT")
            
            if precip is not None:
                pdf.cell(0, 6, f"Precipitation Probability: {precip:.0f}%", new_x="LMARGIN", new_y="NEXT")
            if precip_mm is not None:
                pdf.cell(0, 6, f"Precipitation Sum: {precip_mm:.1f} mm", new_x="LMARGIN", new_y="NEXT")
            if wind is not None:
                pdf.cell(0, 6, f"Max Wind Speed: {wind:.1f} km/h", new_x="LMARGIN", new_y="NEXT")
            if wcode is not None:
                pdf.cell(0, 6, f"Weather Code: {wcode}", new_x="LMARGIN", new_y="NEXT")
            pdf.ln(5)

    # Logistics & Travel Notes if multiple locations on this day
    # Identify unique location sequence for this day in order of scene schedule
    loc_sequence = []
    for entry in day_entries:
        sc = next((s for s in scenes if str(s.id) == str(entry.scene_id)), None)
        if sc and sc.location_id:
            locs_list = project.locations if hasattr(project.locations, '__iter__') else [project.locations]
            loc_obj = next((l for l in locs_list if l and str(l.id) == str(sc.location_id)), None)
            if loc_obj and (not loc_sequence or loc_sequence[-1].id != loc_obj.id):
                loc_sequence.append(loc_obj)

    logistics_notes = []
    if len(loc_sequence) > 1:
        for i in range(len(loc_sequence) - 1):
            loc_a = loc_sequence[i]
            loc_b = loc_sequence[i+1]
            if (loc_a.latitude is not None and loc_a.longitude is not None and
                loc_b.latitude is not None and loc_b.longitude is not None):
                try:
                    from integrations.routing_client import get_travel_duration
                    travel = get_travel_duration(
                        float(loc_a.latitude), float(loc_a.longitude),
                        float(loc_b.latitude), float(loc_b.longitude)
                    )
                    if travel.ok:
                        logistics_notes.append(
                            f"Location Move: '{loc_a.name}' to '{loc_b.name}' is "
                            f"approx. {travel.duration_minutes:.0f} mins drive ({travel.distance_km:.1f} km)."
                        )
                except Exception as e:
                    pass

    # Schedule
    pdf.set_font("helvetica", "B", 14)
    pdf.cell(0, 10, "Shooting Schedule", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    for entry in day_entries:
        sc = next((s for s in scenes if str(s.id) == str(entry.scene_id)), None)
        if not sc: continue
        
        start_str = entry.start_time.strftime("%H:%M") if entry.start_time else "TBD"
        end_str = entry.end_time.strftime("%H:%M") if entry.end_time else "TBD"
        time_str = f"{start_str} - {end_str}"
        
        # Calculate cast call time note (30 mins before)
        if entry.start_time:
            total_mins = entry.start_time.hour * 60 + entry.start_time.minute
            call_mins = max(0, total_mins - 30)
            call_h, call_m = divmod(call_mins, 60)
            cast_call_time_str = f"{call_h:02d}:{call_m:02d}"
        else:
            cast_call_time_str = "TBD"

        # Resolve location details
        loc_name = "No Location"
        loc_address = "No Address Provided"
        if sc.location_id:
            locs_list = project.locations if hasattr(project.locations, '__iter__') else [project.locations]
            loc_obj = next((l for l in locs_list if l and str(l.id) == str(sc.location_id)), None)
            if loc_obj:
                loc_name = loc_obj.name
                if loc_obj.address:
                    loc_address = loc_obj.address

        cast_names = [c.name for c in getattr(sc, 'cast_members', [])]
        cast_str = ", ".join(cast_names) if cast_names else "None"

        # Draw a beautiful bordered block for each scene
        pdf.set_draw_color(200, 200, 200)
        
        # Start X and Y
        start_x = pdf.get_x()
        start_y = pdf.get_y()
        
        # Add padding and content
        pdf.set_xy(start_x + 3, start_y + 3)
        pdf.set_font("helvetica", "B", 11)
        header_text = f"{time_str} | Scene {sc.scene_number} ({sc.setting}) - {sc.title}"
        pdf.cell(0, 6, header_text, new_x="LMARGIN", new_y="NEXT")
        
        pdf.set_font("helvetica", "", 10)
        pdf.set_x(start_x + 3)
        pdf.cell(0, 5, f"Location: {loc_name} ({loc_address})", new_x="LMARGIN", new_y="NEXT")
        
        pdf.set_x(start_x + 3)
        pdf.cell(0, 5, f"Cast Needed: {cast_str}", new_x="LMARGIN", new_y="NEXT")
        
        pdf.set_x(start_x + 3)
        pdf.set_font("helvetica", "I", 9)
        pdf.cell(0, 5, f"Cast Call Time Note: Arrive 30 mins prior at {cast_call_time_str}", new_x="LMARGIN", new_y="NEXT")
        
        end_y = pdf.get_y() + 3
        
        # Draw the surrounding rectangle
        pdf.rect(start_x, start_y, 190, end_y - start_y)
        pdf.set_y(end_y + 4)

    pdf.ln(5)

    if logistics_notes:
        pdf.set_font("helvetica", "B", 12)
        pdf.cell(0, 10, "Logistics & Travel", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("helvetica", "", 10)
        for note in logistics_notes:
            pdf.multi_cell(0, 6, f"- {note}", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(5)
    
    pdf.set_font("helvetica", "B", 12)
    pdf.cell(0, 10, "General Notes", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("helvetica", "", 10)
    pdf.multi_cell(0, 6, "Safety First. In case of emergency, contact the AD immediately.")

    pdf.output(file_path)
    return file_path
