import os
from datetime import datetime
from fpdf import FPDF
from typing import Dict, Any, List, Optional
import json

class CallSheetPDF(FPDF):
    def __init__(self, project_name: str, shoot_day: int, shoot_date: str, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.project_name = project_name
        self.shoot_day = shoot_day
        self.shoot_date = shoot_date

    def header(self):
        # Logo / Header
        self.set_font("helvetica", "B", 18)
        self.cell(0, 10, f"CALL SHEET - {self.project_name.upper()}", align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_font("helvetica", "", 12)
        self.cell(0, 10, f"Shoot Day {self.shoot_day} | Date: {self.shoot_date}", align="C", new_x="LMARGIN", new_y="NEXT")
        self.line(10, 30, 200, 30)
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.cell(0, 10, f"Generated by CineSched | Page {self.page_no()}/{{nb}}", align="C")

def _safe_float(val, default=0.0):
    try:
        return float(val)
    except (ValueError, TypeError):
        return default

def generate_call_sheet(
    project: Any, 
    schedule: Any, 
    day: int, 
    scenes: List[Any], 
    cast: List[Any], 
    user_id: Optional[str] = None
) -> str:
    """
    Generates a PDF call sheet for a specific shoot day.
    If user_id is provided, generates a personalized call sheet (only their scenes).
    Returns the file path to the generated PDF.
    """
    # Create temp directory if not exists
    os.makedirs("/tmp/cinesched", exist_ok=True)
    file_path = f"/tmp/cinesched/callsheet_{project.id}_day_{day}{'_me' if user_id else ''}.pdf"

    # Filter schedule entries for this day
    day_entries = [e for e in schedule.entries if e.shoot_day == day]
    day_entries.sort(key=lambda e: e.start_time or datetime.min.time())
    
    shoot_date_str = "TBD"
    if day_entries and day_entries[0].shoot_date:
        shoot_date_str = day_entries[0].shoot_date.strftime("%Y-%m-%d")

    # If personalized, check if the user is in the cast, and only include their scenes
    personal_cast_member = None
    if user_id:
        # We assume cast model has a user_id or similar link. Wait, does CastMember have user_id?
        # Let's check CastMember schema. 
        # Actually, let's just pass `personal_cast_member` if they are linked.
        personal_cast_member = next((c for c in cast if getattr(c, 'linked_email', None) and c.linked_email != ""), None)
        # We need a robust way to match User to CastMember.
        # This will be refined.
        pass

    pdf = CallSheetPDF(project.name, day, shoot_date_str)
    pdf.add_page()

    # Weather Info (from schedule extra_context if available)
    if schedule.extra_context and "day_forecasts" in schedule.extra_context:
        forecasts = schedule.extra_context["day_forecasts"]
        if str(day) in forecasts:
            weather = forecasts[str(day)]
            pdf.set_font("helvetica", "B", 12)
            pdf.cell(0, 10, "Weather Forecast", new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("helvetica", "", 10)
            
            temp_max = _safe_float(weather.get("temperature_2m_max"))
            temp_min = _safe_float(weather.get("temperature_2m_min"))
            precip = _safe_float(weather.get("precipitation_probability_max"))
            
            pdf.cell(0, 6, f"High: {temp_max}C | Low: {temp_min}C", new_x="LMARGIN", new_y="NEXT")
            pdf.cell(0, 6, f"Precipitation Chance: {precip}%", new_x="LMARGIN", new_y="NEXT")
            if weather.get("weather_code") is not None:
                pdf.cell(0, 6, f"Code: {weather.get('weather_code')}", new_x="LMARGIN", new_y="NEXT")
            pdf.ln(5)

    # Schedule
    pdf.set_font("helvetica", "B", 14)
    pdf.cell(0, 10, "Shooting Schedule", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("helvetica", "B", 10)
    
    # Table Header
    pdf.cell(25, 8, "Time", border=1, align="C")
    pdf.cell(20, 8, "Scene", border=1, align="C")
    pdf.cell(90, 8, "Title & Location", border=1, align="L")
    pdf.cell(55, 8, "Cast Needed", border=1, align="L", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("helvetica", "", 9)
    for entry in day_entries:
        sc = next((s for s in scenes if str(s.id) == str(entry.scene_id)), None)
        if not sc: continue
        
        start_str = entry.start_time.strftime("%H:%M") if entry.start_time else "TBD"
        end_str = entry.end_time.strftime("%H:%M") if entry.end_time else "TBD"
        time_str = f"{start_str}-{end_str}"
        
        cast_str = ", ".join([c.name for c in getattr(sc, 'cast_members', [])])
        title_loc = f"{sc.title} ({sc.setting})"
        if getattr(sc, 'location', None):
            title_loc += f" @ {sc.location.name}"

        x_start = pdf.get_x()
        y_start = pdf.get_y()
        
        pdf.cell(25, 8, time_str, border=1, align="C")
        pdf.cell(20, 8, str(sc.scene_number), border=1, align="C")
        
        # Calculate heights for multicell
        pdf.multi_cell(90, 8, title_loc, border=1, align="L", new_x="RIGHT", new_y="TOP")
        
        # Reset X/Y and do cast
        pdf.set_xy(x_start + 135, y_start)
        pdf.multi_cell(55, 8, cast_str if cast_str else "None", border=1, align="L", new_x="LMARGIN", new_y="NEXT")
        
        new_y = max(pdf.get_y(), y_start + 8)
        pdf.set_y(new_y)

    pdf.ln(10)
    
    pdf.set_font("helvetica", "B", 12)
    pdf.cell(0, 10, "General Notes", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("helvetica", "", 10)
    pdf.multi_cell(0, 6, "Safety First. In case of emergency, contact the AD immediately.")

    pdf.output(file_path)
    return file_path
