import os
from datetime import datetime
from fpdf import FPDF
from typing import Dict, Any, List, Optional
import json

class ProductionBookPDF(FPDF):
    def __init__(self, project_name: str, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.project_name = project_name
        self.current_section = "cover"  # "cover", "day", "summary"
        self.shoot_day = 1
        self.shoot_date = "TBD"

    def header(self):
        if self.current_section == "cover":
            return
        
        self.set_font("helvetica", "B", 14)
        if self.current_section == "day":
            self.cell(0, 8, f"PRODUCTION BOOK - {self.project_name.upper()}", align="C", new_x="LMARGIN", new_y="NEXT")
            self.set_font("helvetica", "", 10)
            self.cell(0, 6, f"Shoot Day {self.shoot_day} | Date: {self.shoot_date}", align="C", new_x="LMARGIN", new_y="NEXT")
        elif self.current_section == "summary":
            self.cell(0, 8, f"PRODUCTION BOOK - {self.project_name.upper()}", align="C", new_x="LMARGIN", new_y="NEXT")
            self.set_font("helvetica", "", 10)
            self.cell(0, 6, "Summary & Planner Reference", align="C", new_x="LMARGIN", new_y="NEXT")
        
        self.line(10, 26, 200, 26)
        self.ln(6)

    def footer(self):
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.cell(0, 10, f"Generated by CineSched | Page {self.page_no()}/{{nb}}", align="C")


def generate_production_book(
    project: Any, 
    schedule: Any, 
    scenes: List[Any], 
    cast: List[Any],
    route_plan: Optional[dict] = None,
    budget_plan: Optional[dict] = None,
) -> str:
    """
    Generates a full Production Book PDF combining all shoot days,
    followed by Cost Plan and Route Plan summaries.
    """
    os.makedirs("/tmp/cinesched", exist_ok=True)
    file_path = f"/tmp/cinesched/production_book_{project.id}.pdf"

    pdf = ProductionBookPDF(project.name)
    
    # ── 1. COVER PAGE ──
    pdf.current_section = "cover"
    pdf.add_page()
    
    # Spacer
    pdf.ln(40)
    
    # Title
    pdf.set_font("helvetica", "B", 26)
    pdf.cell(0, 15, project.name.upper(), align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("helvetica", "B", 18)
    pdf.cell(0, 10, "PRODUCTION BOOK", align="C", new_x="LMARGIN", new_y="NEXT")
    
    pdf.ln(10)
    pdf.set_draw_color(100, 100, 100)
    pdf.line(40, pdf.get_y(), 170, pdf.get_y())
    pdf.ln(15)
    
    # Metadata
    pdf.set_font("helvetica", "", 12)
    total_days = max([e.shoot_day for e in schedule.entries]) if schedule.entries else 0
    pdf.cell(0, 8, f"Total Shoot Days: {total_days}", align="C", new_x="LMARGIN", new_y="NEXT")
    
    # Date range
    sorted_dates = sorted([e.shoot_date for e in schedule.entries if e.shoot_date])
    date_range_str = "TBD"
    if sorted_dates:
        start_date = sorted_dates[0].strftime("%B %d, %Y")
        end_date = sorted_dates[-1].strftime("%B %d, %Y")
        date_range_str = f"{start_date} to {end_date}"
    pdf.cell(0, 8, f"Production Schedule: {date_range_str}", align="C", new_x="LMARGIN", new_y="NEXT")
    
    if project.description:
        pdf.ln(10)
        pdf.set_font("helvetica", "I", 10)
        pdf.multi_cell(0, 6, project.description, align="C")
        
    pdf.ln(40)
    pdf.set_font("helvetica", "", 9)
    pdf.cell(0, 6, f"Generated on {datetime.now().strftime('%Y-%m-%d %H:%M')}", align="C", new_x="LMARGIN", new_y="NEXT")

    # ── 2. PER-DAY CALL SHEETS ──
    pdf.current_section = "day"
    
    # Group entries by day
    from collections import defaultdict
    days_map = defaultdict(list)
    for entry in schedule.entries:
        days_map[entry.shoot_day].append(entry)
        
    sorted_days = sorted(days_map.keys())
    
    for day in sorted_days:
        day_entries = days_map[day]
        day_entries.sort(key=lambda e: e.start_time or datetime.min.time())
        
        shoot_date_str = "TBD"
        if day_entries and day_entries[0].shoot_date:
            shoot_date_str = day_entries[0].shoot_date.strftime("%Y-%m-%d")
            
        pdf.shoot_day = day
        pdf.shoot_date = shoot_date_str
        pdf.add_page()
        
        # Weather Info (from schedule extra_context if available)
        if schedule.extra_context and "day_forecasts" in schedule.extra_context:
            forecasts = schedule.extra_context["day_forecasts"]
            if str(day) in forecasts:
                weather = forecasts[str(day)]
                pdf.set_font("helvetica", "B", 12)
                pdf.cell(0, 10, "Weather Forecast", new_x="LMARGIN", new_y="NEXT")
                pdf.set_font("helvetica", "", 10)
                
                temp_max = weather.get("temperature_2m_max")
                temp_min = weather.get("temperature_2m_min")
                precip = weather.get("precipitation_probability_max")
                precip_mm = weather.get("precipitation_sum_mm")
                wind = weather.get("wind_speed_max_kmh")
                wcode = weather.get("weather_code")
                
                if temp_max is not None and temp_min is not None:
                    pdf.cell(0, 6, f"Temperature Range: {temp_min:.1f}C to {temp_max:.1f}C", new_x="LMARGIN", new_y="NEXT")
                elif temp_max is not None or temp_min is not None:
                    t_val = temp_max if temp_max is not None else temp_min
                    pdf.cell(0, 6, f"Temperature: {t_val:.1f}C", new_x="LMARGIN", new_y="NEXT")
                
                if precip is not None:
                    pdf.cell(0, 6, f"Precipitation Probability: {precip:.0f}%", new_x="LMARGIN", new_y="NEXT")
                if precip_mm is not None:
                    pdf.cell(0, 6, f"Precipitation Sum: {precip_mm:.1f} mm", new_x="LMARGIN", new_y="NEXT")
                if wind is not None:
                    pdf.cell(0, 6, f"Max Wind Speed: {wind:.1f} km/h", new_x="LMARGIN", new_y="NEXT")
                if wcode is not None:
                    pdf.cell(0, 6, f"Weather Code: {wcode}", new_x="LMARGIN", new_y="NEXT")
                pdf.ln(5)

        # Logistics & Travel Notes
        loc_sequence = []
        for entry in day_entries:
            sc = next((s for s in scenes if str(s.id) == str(entry.scene_id)), None)
            if sc and sc.location_id:
                locs_list = project.locations if hasattr(project.locations, '__iter__') else [project.locations]
                loc_obj = next((l for l in locs_list if l and str(l.id) == str(sc.location_id)), None)
                if loc_obj and (not loc_sequence or loc_sequence[-1].id != loc_obj.id):
                    loc_sequence.append(loc_obj)

        logistics_notes = []
        if len(loc_sequence) > 1:
            for i in range(len(loc_sequence) - 1):
                loc_a = loc_sequence[i]
                loc_b = loc_sequence[i+1]
                if (loc_a.latitude is not None and loc_a.longitude is not None and
                    loc_b.latitude is not None and loc_b.longitude is not None):
                    try:
                        from integrations.routing_client import get_travel_duration
                        travel = get_travel_duration(
                            float(loc_a.latitude), float(loc_a.longitude),
                            float(loc_b.latitude), float(loc_b.longitude)
                        )
                        if travel.ok:
                            logistics_notes.append(
                                f"Location Move: '{loc_a.name}' to '{loc_b.name}' is "
                                f"approx. {travel.duration_minutes:.0f} mins drive ({travel.distance_km:.1f} km)."
                            )
                    except:
                        pass

        # Schedule entries
        pdf.set_font("helvetica", "B", 12)
        pdf.cell(0, 10, "Shooting Schedule", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

        for entry in day_entries:
            sc = next((s for s in scenes if str(s.id) == str(entry.scene_id)), None)
            if not sc: continue
            
            start_str = entry.start_time.strftime("%H:%M") if entry.start_time else "TBD"
            end_str = entry.end_time.strftime("%H:%M") if entry.end_time else "TBD"
            time_str = f"{start_str} - {end_str}"
            
            if entry.start_time:
                total_mins = entry.start_time.hour * 60 + entry.start_time.minute
                call_mins = max(0, total_mins - 30)
                call_h, call_m = divmod(call_mins, 60)
                cast_call_time_str = f"{call_h:02d}:{call_m:02d}"
            else:
                cast_call_time_str = "TBD"

            loc_name = "No Location"
            loc_address = "No Address Provided"
            if sc.location_id:
                locs_list = project.locations if hasattr(project.locations, '__iter__') else [project.locations]
                loc_obj = next((l for l in locs_list if l and str(l.id) == str(sc.location_id)), None)
                if loc_obj:
                    loc_name = loc_obj.name
                    if loc_obj.address:
                        loc_address = loc_obj.address

            cast_names = [c.name for c in getattr(sc, 'cast_members', [])]
            cast_str = ", ".join(cast_names) if cast_names else "None"

            pdf.set_draw_color(200, 200, 200)
            start_x = pdf.get_x()
            start_y = pdf.get_y()
            
            pdf.set_xy(start_x + 3, start_y + 3)
            pdf.set_font("helvetica", "B", 10)
            header_text = f"{time_str} | Scene {sc.scene_number} ({sc.setting}) - {sc.title}"
            pdf.cell(0, 5, header_text, new_x="LMARGIN", new_y="NEXT")
            
            pdf.set_font("helvetica", "", 9)
            pdf.set_x(start_x + 3)
            pdf.cell(0, 4, f"Location: {loc_name} ({loc_address})", new_x="LMARGIN", new_y="NEXT")
            
            pdf.set_x(start_x + 3)
            pdf.cell(0, 4, f"Cast Needed: {cast_str}", new_x="LMARGIN", new_y="NEXT")
            
            pdf.set_x(start_x + 3)
            pdf.set_font("helvetica", "I", 8)
            pdf.cell(0, 4, f"Cast Call Time Note: Arrive 30 mins prior at {cast_call_time_str}", new_x="LMARGIN", new_y="NEXT")
            
            end_y = pdf.get_y() + 3
            pdf.rect(start_x, start_y, 190, end_y - start_y)
            pdf.set_y(end_y + 4)

        pdf.ln(3)

        if logistics_notes:
            pdf.set_font("helvetica", "B", 11)
            pdf.cell(0, 8, "Logistics & Travel", new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("helvetica", "", 9)
            for note in logistics_notes:
                pdf.multi_cell(0, 5, f"- {note}", new_x="LMARGIN", new_y="NEXT")
            pdf.ln(3)
        
        pdf.set_font("helvetica", "B", 11)
        pdf.cell(0, 8, "General Notes", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("helvetica", "", 9)
        pdf.multi_cell(0, 5, "Safety First. In case of emergency, contact the AD immediately.")

    # ── 3. SUMMARY SECTION ──
    pdf.current_section = "summary"
    
    # ── A. Route Plan Summary (if exists) ──
    if route_plan and "ordered_stops" in route_plan:
        pdf.add_page()
        pdf.set_font("helvetica", "B", 14)
        pdf.cell(0, 10, "Route Plan Summary", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)
        
        pdf.set_font("helvetica", "", 10)
        trip_type_label = "Round Trip" if route_plan.get("trip_type") == "round_trip" else "One Way"
        pdf.cell(0, 6, f"Trip Style: {trip_type_label}", new_x="LMARGIN", new_y="NEXT")
        pdf.cell(0, 6, f"Total Driving Distance: {route_plan.get('total_distance_km', 0)} km", new_x="LMARGIN", new_y="NEXT")
        pdf.cell(0, 6, f"Total Driving Duration: {route_plan.get('total_duration_min', 0)} mins", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(5)
        
        pdf.set_font("helvetica", "B", 11)
        pdf.cell(0, 8, "Optimized Stop Sequence:", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("helvetica", "", 10)
        
        stops_ids = route_plan["ordered_stops"]
        locs_list = project.locations if hasattr(project.locations, '__iter__') else [project.locations]
        for idx, sid in enumerate(stops_ids):
            loc_name = next((l.name for l in locs_list if l and str(l.id) == sid), "Unknown Location")
            pdf.cell(0, 6, f"{idx + 1}. {loc_name}", new_x="LMARGIN", new_y="NEXT")
            
        pdf.ln(10)

    # ── B. Cost Plan Summary (if exists) ──
    if budget_plan and "categories" in budget_plan:
        pdf.add_page()
        pdf.set_font("helvetica", "B", 14)
        pdf.cell(0, 10, "Cost Plan Summary", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)
        
        pdf.set_font("helvetica", "", 10)
        total_cost = budget_plan.get("total_cost", 0)
        pdf.cell(0, 8, f"Total Calculated Cost: ${total_cost:,.2f}", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(5)
        
        # Table of categories
        pdf.set_font("helvetica", "B", 10)
        pdf.cell(100, 8, "Category", border=1)
        pdf.cell(45, 8, "Cost", border=1, align="R")
        pdf.cell(45, 8, "Calculation Style", border=1, align="C", new_x="LMARGIN", new_y="NEXT")
        
        pdf.set_font("helvetica", "", 9)
        for cat in budget_plan["categories"]:
            amount = cat.get("amount", 0)
            style_label = "Estimate" if cat.get("is_naive", True) else "Optimized"
            
            pdf.cell(100, 8, cat.get("category_name", ""), border=1)
            pdf.cell(45, 8, f"${amount:,.2f}", border=1, align="R")
            pdf.cell(45, 8, style_label, border=1, align="C", new_x="LMARGIN", new_y="NEXT")
            
        pdf.ln(10)

    pdf.output(file_path)
    return file_path
